# HybridOps 工作流程定义 - Pedro Valerio 方法论
# 版本: 1.0.0
# 最后更新: 2026-01-28

name: hybrid-ops-pv
version: "1.0"
description: |
  实现Pedro Valerio方法论的HybridOps工作流程模板，
  用于软件开发中的人类-智能体协作。

metadata:
  author: Pedro Valerio
  license: MIT
  repository: https://github.com/SynkraAI/aios-hybrid-ops-pedro-valerio
  documentation: ../docs/workflow-diagram.md

# 配置
config:
  # 默认委托模式: autonomous | hybrid | human-led
  default_mode: hybrid

  # 需要人类批准的任务类型
  require_human_approval:
    - architecture_decisions
    - security_changes
    - database_migrations
    - production_deployments

  # 智能体可以自主执行的任务
  autonomous_tasks:
    - code_formatting
    - test_execution
    - documentation_updates
    - dependency_updates

# 工作流程阶段
stages:
  - id: planning
    name: 规划阶段
    description: 定义目标和分析需求
    participants:
      human:
        role: decision_maker
        responsibilities:
          - 定义业务目标
          - 设置约束和边界
          - 批准最终计划
      agent:
        role: analyst
        responsibilities:
          - 分析需求
          - 识别风险
          - 提议解决方案
    checkpoints:
      - name: requirements_complete
        type: human_approval
        criteria: 所有需求已记录和验证
      - name: plan_approved
        type: human_approval
        criteria: 实现计划已审查并批准

  - id: design
    name: 设计阶段
    description: 创建和优化技术设计
    participants:
      human:
        role: domain_expert
        responsibilities:
          - 提供上下文
          - 审查设计
          - 做出架构决策
      agent:
        role: designer
        responsibilities:
          - 生成设计选项
          - 记录架构
          - 创建图表
    checkpoints:
      - name: design_review
        type: human_review
        criteria: 设计符合需求和标准
      - name: design_approved
        type: human_approval
        criteria: 最终设计已签署

  - id: implementation
    name: 实现阶段
    description: 执行实现计划
    participants:
      human:
        role: reviewer
        responsibilities:
          - 代码审查
          - 提供反馈
          - 解除智能体的阻碍
      agent:
        role: implementer
        responsibilities:
          - 编写代码
          - 编写测试
          - 自审查
    checkpoints:
      - name: code_complete
        type: agent_report
        criteria: 所有任务已实现
      - name: code_reviewed
        type: human_review
        criteria: 代码符合质量标准
      - name: tests_passing
        type: automated
        criteria: 所有测试通过

  - id: quality_assurance
    name: 质量保证阶段
    description: 验证质量并为发布做准备
    participants:
      human:
        role: approver
        responsibilities:
          - 定义测试标准
          - 审查测试结果
          - 最终批准
      agent:
        role: tester
        responsibilities:
          - 执行测试
          - 生成报告
          - 修复问题
    checkpoints:
      - name: qa_complete
        type: automated
        criteria: 所有质量门已通过
      - name: release_approved
        type: human_approval
        criteria: 准备生产发布

# 转换
transitions:
  - from: planning
    to: design
    condition: plan_approved

  - from: design
    to: implementation
    condition: design_approved

  - from: implementation
    to: quality_assurance
    condition: code_reviewed AND tests_passing

  - from: quality_assurance
    to: complete
    condition: release_approved

  # 回滚转换
  - from: design
    to: planning
    condition: requirements_changed
    type: rollback

  - from: implementation
    to: design
    condition: design_issues_found
    type: rollback

  - from: quality_assurance
    to: implementation
    condition: qa_failed
    type: rollback

# 任务委托规则
delegation:
  # 自主执行的标准
  autonomous_criteria:
    - task_type in config.autonomous_tasks
    - risk_level == "low"
    - no_human_dependencies

  # 混合执行的标准
  hybrid_criteria:
    - task_type not in config.require_human_approval
    - risk_level in ["low", "medium"]

  # 人类主导执行的标准
  human_led_criteria:
    - task_type in config.require_human_approval
    - risk_level == "high"
    - critical_path == true

# 与AIOS集成
aios_integration:
  agents:
    - agent: dev
      stages: [implementation]
      role: implementer

    - agent: qa
      stages: [quality_assurance]
      role: tester

    - agent: architect
      stages: [planning, design]
      role: analyst

    - agent: pm
      stages: [planning, quality_assurance]
      role: coordinator

  quality_gates:
    layer1:
      stage: implementation
      automated: true

    layer2:
      stage: quality_assurance
      human_review: true

    layer3:
      stage: quality_assurance
      human_approval: true

# 通知
notifications:
  channels:
    - type: slack
      events: [stage_complete, approval_needed, blocked]

    - type: email
      events: [release_approved, rollback_triggered]

    - type: github
      events: [pr_created, pr_merged]

# 指标
metrics:
  track:
    - cycle_time_per_stage
    - delegation_ratio
    - approval_turnaround_time
    - rollback_frequency
    - agent_autonomy_score

  thresholds:
    approval_turnaround: 4h
    stage_cycle_time: 24h
    agent_autonomy_target: 0.6

# 模板
templates:
  planning_document: |
    ## 目标
    {{ objectives }}

    ## 需求
    {{ requirements }}

    ## 约束
    {{ constraints }}

    ## 建议方法
    {{ approach }}

  handoff_context: |
    ## 当前状态
    {{ current_state }}

    ## 已完成工作
    {{ completed }}

    ## 待处理项目
    {{ pending }}

    ## 阻碍
    {{ blockers }}

# 导出
exports:
  - stages
  - transitions
  - delegation
  - aios_integration
